version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - ./docker/init.sh:/docker-entrypoint-initdb.d/init.sh
      - db:/var/lib/postgresql/data

volumes:
  db: